name: Tests
on: push


env:
  REGISTRY: ghcr.io


jobs:
  e2e:
    name: ğŸš€ E2E
    strategy:
      matrix:
        project: [ 'Mobile Chrome', 'Mobile Safari' ]
    permissions:
      packages: read
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: gh search repos --owner akdasa-studios --match name shlokas --visibility public | while read -r repo _; do gh repo clone "$repo" "$repo"; done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: ğŸ“¥ Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 'akdasa-studios/shlokas-server'

      # - name: ğŸ³ Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: shlokas-container
      #     path: /tmp

      # - name: ğŸ³ Load Docker image
      #   run: |
      #     docker load --input /tmp/shlokas-container.tar
      #     docker image ls -a

      # # - name: Environment
      # #   uses: isbang/compose-action@v1.4.1
      # #   with:
      # #     compose-file: |
      # #       docker-compose.yml
      # #       docker-compose.testing.yml
      # #       docker-compose.testing.ci.yml
      # #     down-flags: "--volumes"

      # - name: ğŸ³ Start server
      #   run: ./shlokas.run.sh testing
      #   shell: bash

      # - name: ğŸ§ª Testing
      #   uses: addnab/docker-run-action@v3
      #   with:
      #     image: ghcr.io/akdasa-studios/shlokas-e2e:latest
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     options: |
      #       -e CI=1
      #       -e SHLOKAS_URL=http://shlokas
      #       -e MAIL_URL=http://mail:1080
      #       -v ${{ github.workspace }}/output:/e2e/output
      #       --network shlokas
      #     shell: bash
      #     run: |
      #       npm i
      #       npx playwright test --project="${{ matrix.project }}"

      # - name: ğŸšš  [Artifacts] Upload
      #   if: ${{ failure() }}
      #   uses: actions/upload-artifact@v3.1.2
      #   with:
      #     name: e2e-${{ matrix.project }}
      #     path: output/
      #     retention-days: 5
